export const OfferSector = {
  COMMERCE: 'COMMERCE',
  RESTAURATION_HOTELLERIE: 'RESTAURATION_HOTELLERIE',
  BTP: 'BTP',
  INDUSTRIE: 'INDUSTRIE',
  LOGISTIQUE_TRANSPORT: 'LOGISTIQUE_TRANSPORT',
  SANTE_SOCIAL: 'SANTE_SOCIAL',
  INFORMATIQUE_NUMERIQUE: 'INFORMATIQUE_NUMERIQUE',
  ADMINISTRATIF_GESTION: 'ADMINISTRATIF_GESTION',
  BANQUE_ASSURANCE: 'BANQUE_ASSURANCE',
  COMMUNICATION_MARKETING: 'COMMUNICATION_MARKETING',
  AGRICULTURE_ENVIRONNEMENT: 'AGRICULTURE_ENVIRONNEMENT',
  ART_CULTURE: 'ART_CULTURE',
  EDUCATION_FORMATION: 'EDUCATION_FORMATION',
  BEAUTE_BIEN_ETRE: 'BEAUTE_BIEN_ETRE',
  SPORT_ANIMATION: 'SPORT_ANIMATION',
  AUTRE: 'AUTRE',
} as const;

export type OfferSector = (typeof OfferSector)[keyof typeof OfferSector];
